### PR TITLE
fix: US138596 - Add skeletonization to Fill in the Blank

### PR DESCRIPTION
**Pull request by tdevos-d2l**
[US138596](https://rally1.rallydev.com/#/?detail=/userstory/632864225087&fdp=true): [Consistent Evaluation][Quizzes][UI][Questions] Add skeletonization to Fill in the Blank

- Added skeleton for fill in the blank question type
- Fixed docs

image

### CODE REVIEW

**Review by maddiegabriel — APPROVED** [review]
stunning

**Review by JamieTran — APPROVED** [review]
☠️ 👑

**Comment by JamieTran** [comment]
I would like to see RTL support as well :)

**Comment by JamieTran** [comment]
jk ur a beast

**Pull request merged**
